mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: CO - zhuhai.uk
  type: vless
  server: 157.137.225.233
  port: 62145
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
- name: SG - zhuhai.uk
  type: anytls
  server: yazhouany02.downapptwo.cc
  port: 47053
  password: 29204996-a723-4291-8c70-30843b592d40
  udp: true
  skip-cert-verify: true
- name: PL - zhuhai.uk
  type: vless
  server: 31.59.125.49
  port: 443
  uuid: 423b1d79-08c4-403f-9d5e-c541f791b55f
  flow: xtls-rprx-vision
  tls: true
  servername: eu-central.cendora.ru
  skip-cert-verify: true
  client-fingerprint: firefox
  reality-opts:
    public-key: b-Cm9hX-3UHsS1L_lnUB6AMjuKhlN1IDdBbZ506itjI
    short-id: 00bca5982f82d083
- name: GB - zhuhai.uk
  type: ss
  server: 18.171.210.5
  port: 443
  cipher: aes-256-cfb
  password: amazonskr05
- name: DE - zhuhai.uk
  type: ss
  server: 152.70.21.245
  port: 59924
  cipher: 2022-blake3-chacha20-poly1305
  password: GKK6Jd16pxKLp+jgEMOjGOWXx3svXEXvq8DwRaqHbuw=
- name: KR - zhuhai.uk
  type: http
  server: 5ae821d5-tki800-tlwmty-1gevg.kr.oshuawei.com
  port: 31433
  username: f02ee2b4-d760-11ec-bd7c-f23c913c8d2b
  password: f02ee2b4-d760-11ec-bd7c-f23c913c8d2b
  tls: true
  skip-cert-verify: true
- name: US - zhuhai.uk
  type: http
  server: 138.199.35.207
  port: 9002
  username: 'null'
  password: None
  tls: true
  sni: 138.199.35.207
  skip-cert-verify: true
- name: LV - zhuhai.uk
  type: http
  server: 109.248.147.66
  port: 443
  tls: true
  skip-cert-verify: true
- name: NL - zhuhai.uk
  type: vless
  server: 199.232.78.159
  port: 443
  uuid: 27315937-5479-49fd-867d-6b2f17246708
  tls: true
  servername: ssl.fastly.com
  client-fingerprint: chrome
  network: ws
  ws-opts:
    path: "/TELEGRAM_NUFiLTER,TELEGRAM_NUFiLTER,TELEGRAM_NUFiLTER,TELEGRAM_NUFiLTER,TELEGRAM_NUFiLTER,TELEGRAM_NUFiLTER,TELEGRAM_NUFiLTER"
    headers:
      Host: pan1.global.ssl.fastly.net
- name: US - zhuhai.uk 02
  type: http
  server: 138.199.35.202
  port: 9002
  username: 'null'
  password: 'null'
  tls: true
  sni: 138.199.35.202
  skip-cert-verify: true
- name: SG - zhuhai.uk 02
  type: anytls
  server: test01.y1static-content-distribution.shop
  port: 47096
  password: 29204996-a723-4291-8c70-30843b592d40
  udp: true
  sni: xjp33.pulsarcore.site
  skip-cert-verify: true
- name: SG - zhuhai.uk 03
  type: anytls
  server: test01.y1static-content-distribution.shop
  port: 16406
  password: 29204996-a723-4291-8c70-30843b592d40
  udp: true
  sni: yz203.y1static-content-distribution.shop
- name: US - zhuhai.uk 03
  type: http
  server: 138.199.35.200
  port: 9002
  tls: true
  skip-cert-verify: true
- name: US - zhuhai.uk 04
  type: ss
  server: 141.148.165.216
  port: 50356
  cipher: 2022-blake3-chacha20-poly1305
  password: 3xPP6iNfdLgydSGSQeEvX8FC3wofQ3e7GgGFUH8O1Ao=
- name: GR - zhuhai.uk
  type: http
  server: 149.22.85.78
  port: 443
  tls: true
  sni: 149.22.85.78
  skip-cert-verify: true
- name: US - zhuhai.uk 05
  type: http
  server: 138.199.35.218
  port: 9002
  tls: true
  sni: 138.199.35.218
  skip-cert-verify: true
- name: SG - zhuhai.uk 04
  type: ss
  server: 161.118.203.141
  port: 56927
  cipher: 2022-blake3-chacha20-poly1305
  password: F2M12ztwS+zxs2LT5+VDiHt3FuhbuzBMYRiswQM8b74=
- name: US - zhuhai.uk 06
  type: http
  server: kimberlymilano.icu
  port: 443
  tls: true
- name: CO - zhuhai.uk 02
  type: vless
  server: 149.130.185.186
  port: 62145
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
- name: PT - zhuhai.uk
  type: http
  server: 149.22.86.14
  port: 443
  tls: true
  skip-cert-verify: true
- name: KR - zhuhai.uk 02
  type: hysteria2
  server: 150-230-252-217.liao.kdns.fr
  port: 50160
  password: 9cfc9458e48c028ec03ff86ebc71c744
  sni: 150-230-252-217.liao.kdns.fr
- name: FI - zhuhai.uk
  type: http
  server: extension.intern3t.ru
  port: 8891
  username: 85efca17026d85555ffc9b651149b5b7
  password: 85efca17026d85555ffc9b651149b5b7
  tls: true
- name: DE - zhuhai.uk 02
  type: ss
  server: 89.168.109.144
  port: 59924
  cipher: 2022-blake3-chacha20-poly1305
  password: Mr13/A/FrxRXiwl0/lVDceMyzGzsOg1SgX/hcIsDM5Q=
- name: US - zhuhai.uk 07
  type: http
  server: 138.199.35.215
  port: 9002
  tls: true
  skip-cert-verify: true
- name: NL - zhuhai.uk 02
  type: vless
  server: 92.5.234.124
  port: 62145
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
- name: NL - zhuhai.uk 03
  type: vless
  server: 188.190.26.243
  port: 443
  uuid: 9ce4c9e2-1dcc-abe8-9abf-9bf8bc1269f6
  tls: true
  servername: 8.o.8.e.t.g.7.w.8.n.e.1.l.e.us.art-us.kdns.fr
  client-fingerprint: chrome
  network: ws
  ws-opts:
    path: "/pg/10086-dfc816f117c49173"
    headers:
      Host: 8.o.8.e.t.g.7.w.8.n.e.1.l.e.us.art-us.kdns.fr
- name: US - zhuhai.uk 08
  type: http
  server: 138.199.35.210
  port: 9002
  username: 'null'
  password: 'null'
  tls: true
  skip-cert-verify: true
- name: JP - zhuhai.uk
  type: socks5
  server: 8.209.236.192
  port: 1080
  username: '123456'
  password: '123456'
- name: HK - zhuhai.uk
  type: hysteria2
  server: 31.57.248.176
  port: 50160
  password: b0917015b656b3dd2286b5633af0c5c1
  sni: www.bing.com
  skip-cert-verify: true
- name: HK - zhuhai.uk 02
  type: socks5
  server: 43.100.43.112
  port: 3060
  username: '123'
  password: '123'
- name: TH - zhuhai.uk
  type: ss
  server: 103.169.67.34
  port: 65443
  cipher: aes-256-cfb
  password: 7eadc6dbe2ae
- name: MY - zhuhai.uk
  type: ss
  server: 118.107.222.231
  port: 65443
  cipher: aes-256-cfb
  password: 7eadc6dbe2ae
- name: CO - zhuhai.uk 01
  type: vless
  server: 158.247.120.174
  port: 62145
  uuid: 8fb65472-5957-4f64-ba2d-b5812b2f155a
  udp: true
  network: tcp
- name: JP - zhuhai.uk 02
  type: vless
  server: 154.31.114.248
  port: 50159
  uuid: d56624b2-35bb-468c-9b2a-e0b0df7230c1
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: www.cloudflare.com
  client-fingerprint: chrome
  reality-opts:
    public-key: j4QXngGuJkUGwRj4XIrfHRohYYuEfnJlX4cvCE-WklA
    short-id: '091e1c5db8451757'
- name: JP - zhuhai.uk 01
  type: vless
  server: 162.141.131.102
  port: 50159
  uuid: 063e01c2-4c0f-418e-9375-3cc1312f635b
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: www.cloudflare.com
  client-fingerprint: chrome
  reality-opts:
    public-key: fLtEa_5BiN89xQDypfFMOu5o6DoUf6ch42jGdkXy6zE
    short-id: 7f24526f7307c07a
- name: SE - zhuhai.uk 01
  type: vless
  server: 88.216.189.177
  port: 443
  uuid: bd1b4bd2-a312-433d-ae7b-d5d28f50af2a
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: id.vk.com
  client-fingerprint: firefox
  reality-opts:
    public-key: AjJEU0yOwxU1qq-6-M32xKTOOc0xI4dpTiRp5EzXIRM
    short-id: '49'
- name: AT - zhuhai.uk 01
  type: vless
  server: 152.53.1.40
  port: 443
  uuid: edde565e-41f5-400e-84ea-7b87a3e84488
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: at.quattro-tech.ru
  client-fingerprint: qq
  reality-opts:
    public-key: 10rVZPoOUP1TlQviIAsQ_jAROX0fRQxH0C92nq_zGQc
    short-id: 43dcff53849b81e6
- name: NO - zhuhai.uk 01
  type: vless
  server: 151.242.168.69
  port: 335
  uuid: 10000025-9365-7547-f000-30f4f61aa020
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: onlineraceentry.co.uk
  client-fingerprint: chrome
  skip-cert-verify: true
  reality-opts:
    public-key: XJhq5Vpqo6j5Xsd56EMAK8--8EWBZWc3tjf-WFnInio
    short-id: ec2213ae33d5b43f
proxy-groups:
- name: 选择出口
  type: select
  proxies:
  - DIRECT
  - CO - zhuhai.uk
  - SG - zhuhai.uk
  - PL - zhuhai.uk
  - GB - zhuhai.uk
  - DE - zhuhai.uk
  - KR - zhuhai.uk
  - US - zhuhai.uk
  - LV - zhuhai.uk
  - NL - zhuhai.uk
  - US - zhuhai.uk 02
  - SG - zhuhai.uk 02
  - SG - zhuhai.uk 03
  - US - zhuhai.uk 03
  - US - zhuhai.uk 04
  - GR - zhuhai.uk
  - US - zhuhai.uk 05
  - SG - zhuhai.uk 04
  - US - zhuhai.uk 06
  - CO - zhuhai.uk 02
  - PT - zhuhai.uk
  - KR - zhuhai.uk 02
  - FI - zhuhai.uk
  - DE - zhuhai.uk 02
  - US - zhuhai.uk 07
  - NL - zhuhai.uk 02
  - NL - zhuhai.uk 03
  - US - zhuhai.uk 08
  - JP - zhuhai.uk
  - HK - zhuhai.uk
  - HK - zhuhai.uk 02
  - TH - zhuhai.uk
  - MY - zhuhai.uk
  - CO - zhuhai.uk 01
  - JP - zhuhai.uk 02
  - JP - zhuhai.uk 01
  - SE - zhuhai.uk 01
  - AT - zhuhai.uk 01
  - NO - zhuhai.uk 01
rules:
- GEOSITE,CN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,选择出口
