mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: US - zhuhai.uk
  type: http
  server: 138.199.35.206
  port: 9002
  username: 'null'
  password: 'null'
  tls: true
  sni: 138.199.35.206
  skip-cert-verify: true
- name: JP - zhuhai.uk
  type: http
  server: fan.571589.xyz
  port: 443
  username: bnVsbDpudWxs
  tls: true
- name: US - zhuhai.uk 02
  type: http
  server: 138.199.35.209
  port: 9002
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk
  type: http
  server: 193.176.84.33
  port: 9002
  username: 'null'
  password: None
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 02
  type: http
  server: 193.176.84.25
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: US - zhuhai.uk 03
  type: http
  server: 138.199.35.218
  port: 9002
  username: 'null'
  password: None
  tls: true
  sni: 138.199.35.218
  skip-cert-verify: true
- name: US - zhuhai.uk 04
  type: http
  server: 138.199.35.214
  port: 9002
  username: 'null'
  password: 'null'
  tls: true
  skip-cert-verify: true
- name: FI - zhuhai.uk
  type: vless
  server: 171.22.129.56
  port: 2053
  uuid: 9f5b9ca7-d0bb-4e50-a3ca-acf5968027fc
  flow: xtls-rprx-vision
  tls: true
  servername: fi-one.quiet-rogue.site
  client-fingerprint: firefox
  reality-opts:
    public-key: AKUQO-fKsD19FFBxNq5XTFCRXWDZfes4zJjRINY1KUI
    short-id: beff3ff061a64cfd
- name: US - zhuhai.uk 05
  type: http
  server: 138.199.35.208
  port: 9002
  tls: true
  skip-cert-verify: true
- name: NL - zhuhai.uk
  type: http
  server: 84.17.47.149
  port: 9002
  username: 'null'
  password: 'null'
  tls: true
  sni: 84.17.47.149
  skip-cert-verify: true
- name: RO - zhuhai.uk 03
  type: http
  server: 193.176.84.39
  port: 9002
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 04
  type: http
  server: 193.176.84.34
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: GB - zhuhai.uk
  type: http
  server: 185.235.0.66
  port: 443
  tls: true
  skip-cert-verify: true
- name: US - zhuhai.uk 06
  type: http
  server: 138.199.35.212
  port: 9002
  tls: true
  sni: 138.199.35.212
  skip-cert-verify: true
- name: US - zhuhai.uk 07
  type: http
  server: 138.199.35.199
  port: 9002
  username: 'null'
  password: 'null'
  tls: true
  skip-cert-verify: true
- name: JP - zhuhai.uk 02
  type: http
  server: fan.571589.xyz
  port: 443
  username: 'null'
  password: 'null'
  tls: true
  sni: fan.571589.xyz
- name: RO - zhuhai.uk 05
  type: http
  server: 193.176.84.29
  port: 9002
  username: 'null'
  password: 'null'
  tls: true
  skip-cert-verify: true
- name: US - zhuhai.uk 08
  type: anytls
  server: anytls2.864106.xyz
  port: 19000
  password: github.com/Alvin9999-newpac/fanqiang
  udp: true
  sni: anytls2.864106.xyz
  skip-cert-verify: true
- name: ID - zhuhai.uk
  type: http
  server: sr2-id.freeconnect.link
  port: 9251
  username: freeuser1
  password: freeuser1
  tls: true
  skip-cert-verify: true
- name: DE - zhuhai.uk
  type: http
  server: 141.17.83.73
  port: 443
  tls: true
  skip-cert-verify: true
- name: JP - zhuhai.uk 03
  type: http
  server: fan.571589.xyz
  port: 443
  tls: true
  sni: fan.571589.xyz
  skip-cert-verify: true
- name: HK - zhuhai.uk
  type: socks5
  server: 47.239.116.165
  port: 1080
  username: admin
  password: admin
- name: HK - zhuhai.uk 02
  type: vless
  server: 207.57.131.123
  port: 26631
  uuid: 906f32ff-9293-46ee-a694-a5eee40b8b42
  flow: xtls-rprx-vision
  tls: true
  servername: www.cloudflare.com
  skip-cert-verify: true
  client-fingerprint: chrome
  reality-opts:
    public-key: x2oZng_IPNINd3JLak1Rtv05OdkwgChhgHzBT7Z3byQ
- name: KR - zhuhai.uk
  type: socks5
  server: 121.169.46.116
  port: 1090
  username: VDJjbE0wUWxNMFE2Og==
- name: SG - zhuhai.uk
  type: ss
  server: 138.2.85.221
  port: 56927
  cipher: 2022-blake3-chacha20-poly1305
  password: Ncg2e0WWFTuObHDiFL0qupBKuPSc5pVF1GTCMvVtNmg=
- name: SG - zhuhai.uk 02
  type: vless
  server: cfyes.ziyoufly.xyz
  port: 443
  uuid: 3b578f92-da29-48cb-b037-40d2ef032afe
  tls: true
  servername: cf-uh-sg01-2.23523463.xyz
  client-fingerprint: chrome
  network: ws
  ws-opts:
    path: "/ziyou"
    headers:
      Host: cf-uh-sg01-2.23523463.xyz
- name: LT - zhuhai.uk 02
  type: vless
  server: 88.119.176.24
  port: 443
  uuid: ae8e0f7d-b661-41ca-b55d-d8c383adb2f8
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: lit9.helper-internet.com
  client-fingerprint: firefox
  reality-opts:
    public-key: W-zf_ncm9sYALF5EqvUsxqTkYGdAw-tQczT2SqwVMGE
    short-id: ff776ff77be48b88
- name: LT - zhuhai.uk 01
  type: vless
  server: lit9.helper-internet.com
  port: 443
  uuid: ae8e0f7d-b661-41ca-b55d-d8c383adb2f8
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: lit9.helper-internet.com
  client-fingerprint: chrome
  reality-opts:
    public-key: W-zf_ncm9sYALF5EqvUsxqTkYGdAw-tQczT2SqwVMGE
    short-id: ff776ff77be48b88
proxy-groups:
- name: 选择出口
  type: select
  proxies:
  - DIRECT
  - US - zhuhai.uk
  - JP - zhuhai.uk
  - US - zhuhai.uk 02
  - RO - zhuhai.uk
  - RO - zhuhai.uk 02
  - US - zhuhai.uk 03
  - US - zhuhai.uk 04
  - FI - zhuhai.uk
  - US - zhuhai.uk 05
  - NL - zhuhai.uk
  - RO - zhuhai.uk 03
  - RO - zhuhai.uk 04
  - GB - zhuhai.uk
  - US - zhuhai.uk 06
  - US - zhuhai.uk 07
  - JP - zhuhai.uk 02
  - RO - zhuhai.uk 05
  - US - zhuhai.uk 08
  - ID - zhuhai.uk
  - DE - zhuhai.uk
  - JP - zhuhai.uk 03
  - HK - zhuhai.uk
  - HK - zhuhai.uk 02
  - KR - zhuhai.uk
  - SG - zhuhai.uk
  - SG - zhuhai.uk 02
  - LT - zhuhai.uk 02
  - LT - zhuhai.uk 01
rules:
- GEOSITE,CN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,选择出口
