mixed-port: 7890
allow-lan: false
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
proxies:
- name: US - zhuhai.uk
  type: http
  server: 20.42.108.114
  port: 443
  tls: true
  skip-cert-verify: true
- name: US - zhuhai.uk 02
  type: http
  server: 71.43.26.234
  port: 443
  tls: true
  skip-cert-verify: true
- name: RU - zhuhai.uk
  type: http
  server: 82.147.71.46
  port: 443
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk
  type: vless
  server: 109.104.106.149
  port: 443
  uuid: 87fd990d-ca93-440a-bbd4-e8281c4a0910
  flow: xtls-rprx-vision
  tls: true
  servername: d3-ro.cloud-cdn.xyz
  client-fingerprint: edge
  reality-opts:
    public-key: a_v5l6R-rpVGlENLeONW4sz-GdRwIoDqISOWXGov8nw
    short-id: 87709fed663228e5
- name: US - zhuhai.uk 03
  type: http
  server: 138.199.35.201
  port: 9002
  username: 'null'
  password: None
  tls: true
  skip-cert-verify: true
- name: KR - zhuhai.uk
  type: socks5
  server: 121.169.46.116
  port: 1090
  username: VDJjbE0wUWxNMFE2Og==
- name: US - zhuhai.uk 04
  type: http
  server: 44.239.226.15
  port: 443
  tls: true
  skip-cert-verify: true
- name: ID - zhuhai.uk
  type: vless
  server: funagfr.alixxplay.com
  port: 61847
  uuid: 57beeeb0-03fc-4fc9-94da-7604488a7134
  flow: xtls-rprx-vision
  tls: true
  servername: www.lamer.com.sg
  client-fingerprint: ios
  reality-opts:
    public-key: BTVKTYNHnuv3850vXEU15GVgfp5S0Dz20jueg-FSgAQ
    short-id: c761f990d786f2
- name: JP - zhuhai.uk
  type: vless
  server: funagfr.alixxplay.com
  port: 46530
  uuid: 57beeeb0-03fc-4fc9-94da-7604488a7134
  flow: xtls-rprx-vision
  tls: true
  servername: iosapps.itunes.apple.com
  client-fingerprint: ios
  reality-opts:
    public-key: HyqKpSHY4gS8aE65sGpvUkWNJj0JgGRBjsS4MFzVbhA
    short-id: 6cdfb8b5878caf8d
- name: SG - zhuhai.uk
  type: vless
  server: funagfr.alixxplay.com
  port: 57541
  uuid: 57beeeb0-03fc-4fc9-94da-7604488a7134
  flow: xtls-rprx-vision
  tls: true
  servername: www.lamer.com.sg
  client-fingerprint: ios
  reality-opts:
    public-key: hAtfAzXQrbxyqiK3b2XrsxZ35sWiN8iqp0LvjKr9_DE
    short-id: 22b19630280c3f
- name: HK - zhuhai.uk
  type: socks5
  server: 47.239.98.42
  port: 1080
  username: abc123
  password: abc123
- name: RO - zhuhai.uk 02
  type: http
  server: 193.176.84.32
  port: 9002
  tls: true
  sni: www.bing.com
  skip-cert-verify: true
- name: TW - zhuhai.uk
  type: vless
  server: 34.80.248.240
  port: 443
  uuid: 31a40f42-4ad6-4a32-a760-71102b459584
  tls: true
  servername: www.cloudflare.com
  client-fingerprint: chrome
  reality-opts:
    public-key: qvekI7tKB1NDnZA6JcS_24aV4n8mlCbI3SFvkRr22wg
    short-id: d74a6321deec9f31
- name: SG - zhuhai.uk 02
  type: vless
  server: sgip.harry.lv
  port: 443
  uuid: 5d75a660-f04e-4301-a41b-d394bae03970
  tls: true
  servername: sgcf.harry.lv
  client-fingerprint: chrome
  network: ws
  ws-opts:
    path: "/sg"
    headers:
      Host: sgcf.harry.lv
- name: US - zhuhai.uk 05
  type: http
  server: 24.142.229.178
  port: 8090
  tls: true
  skip-cert-verify: true
- name: SG - zhuhai.uk 03
  type: anytls
  server: 2603:c024:4524:3400:0:7caf:8cfa:add3
  port: 8443
  password: oraAny_8nQ5wT1zR
  udp: true
  sni: sg.liujiaqi.top
- name: SG - zhuhai.uk 04
  type: vless
  server: funagfr.alixxplay.com
  port: 30322
  uuid: 57beeeb0-03fc-4fc9-94da-7604488a7134
  flow: xtls-rprx-vision
  tls: true
  servername: www.lamer.com.sg
  client-fingerprint: ios
  reality-opts:
    public-key: WIQGJ43m8ym13-VZ57mAtWY5vOwHMHEpnLV8caw2-kA
    short-id: f38326f99edf
- name: NL - zhuhai.uk
  type: http
  server: 51.158.243.91
  port: 443
  username: 'null'
  password: None
  tls: true
  sni: 51.158.243.91
  skip-cert-verify: true
- name: FR - zhuhai.uk
  type: vless
  server: 34.155.221.142
  port: 443
  uuid: d619964d-26d6-452d-9860-6f058f03ba8e
  tls: true
  servername: www.cloudflare.com
  client-fingerprint: chrome
  reality-opts:
    public-key: 6tH_NDFcxWn60B3s-MgrkBTU2yUUBY42ZG1av50Ywhk
    short-id: ae682368818bd6c5
- name: SG - zhuhai.uk 05
  type: vless
  server: 35.185.179.62
  port: 443
  uuid: 5567cac6-2a32-4318-83cd-7df3a9eebbd7
  tls: true
  servername: www.cloudflare.com
  skip-cert-verify: true
  client-fingerprint: chrome
  reality-opts:
    public-key: hJCcmOf_ECJ3GUfHUjsgfcFKcgGb22H7cz_m_FvcVm4
    short-id: eb97ce837da2f6ad
- name: RO - zhuhai.uk 03
  type: http
  server: 193.176.84.22
  port: 9002
  tls: true
  skip-cert-verify: true
- name: HK - zhuhai.uk 02
  type: vless
  server: 14.17.78.146
  port: 14343
  uuid: 1b60cff4-49ce-4bf3-9027-e4f9c47d6158
  flow: xtls-rprx-vision
  tls: true
  servername: thuk.huaweiyouxuan.com
- name: US - zhuhai.uk 06
  type: http
  server: 138.199.35.206
  port: 9002
  tls: true
  skip-cert-verify: true
- name: RO - zhuhai.uk 04
  type: http
  server: 193.176.84.27
  port: 9002
  tls: true
  skip-cert-verify: true
- name: KR - zhuhai.uk 02
  type: socks5
  server: 121.169.46.116
  port: 1090
  username: VkRKamJFMHdVV3hOTUZFMk9nPT06
- name: FR - zhuhai.uk 01
  type: vless
  server: 45.131.212.231
  port: 443
  uuid: 19513b1b-d29a-4f3e-ba9a-888261e4e048
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: sellflow.org
  client-fingerprint: firefox
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
- name: IL - zhuhai.uk 01
  type: vless
  server: 34.165.56.30
  port: 443
  uuid: 0c40bce9-8710-4820-8f22-0742b61df999
  udp: true
  network: tcp
  tls: true
  servername: www.cloudflare.com
  client-fingerprint: chrome
  reality-opts:
    public-key: AeQDUAVCESyA1hFkw6lENmgWAY3sBH9CFPpPAddPwVc
    short-id: fffff8acddadcac3
proxy-groups:
- name: 选择出口
  type: select
  proxies:
  - DIRECT
  - US - zhuhai.uk
  - US - zhuhai.uk 02
  - RU - zhuhai.uk
  - RO - zhuhai.uk
  - US - zhuhai.uk 03
  - KR - zhuhai.uk
  - US - zhuhai.uk 04
  - ID - zhuhai.uk
  - JP - zhuhai.uk
  - SG - zhuhai.uk
  - HK - zhuhai.uk
  - RO - zhuhai.uk 02
  - TW - zhuhai.uk
  - SG - zhuhai.uk 02
  - US - zhuhai.uk 05
  - SG - zhuhai.uk 03
  - SG - zhuhai.uk 04
  - NL - zhuhai.uk
  - FR - zhuhai.uk
  - SG - zhuhai.uk 05
  - RO - zhuhai.uk 03
  - HK - zhuhai.uk 02
  - US - zhuhai.uk 06
  - RO - zhuhai.uk 04
  - KR - zhuhai.uk 02
  - FR - zhuhai.uk 01
  - IL - zhuhai.uk 01
rules:
- GEOSITE,CN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,选择出口
