proxies:
- name: GB - zhuhai.uk 02
  type: vless
  server: 5.152.223.193
  port: 443
  uuid: f09a0e10-a32f-4c77-9cb6-63b0823b5ad7
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: strapi.io
  client-fingerprint: firefox
  reality-opts:
    public-key: SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY
    short-id: fd55b698ee8c3629
- name: GB - zhuhai.uk 04
  type: vless
  server: 5.152.223.97
  port: 443
  uuid: be5b6ad6-8184-4b63-82ac-3bc00c09c98c
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: strapi.io
  client-fingerprint: chrome
  reality-opts:
    public-key: IFEZmwpGK7VCuDj3kmVdyMn7vUIG8Sntc6TG4eIS3xs
    short-id: 1aa9f3c9021280c0
- name: GB - zhuhai.uk 03
  type: vless
  server: 138.124.180.137
  port: 443
  uuid: 5234b2b7-5e07-422c-8159-d62a676c00c6
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: www.apple.com
  client-fingerprint: chrome
  reality-opts:
    public-key: GBdkyDLfr0LIZo_94Xv8ycAKOmkjArYzwJAEMhuXX2c
    short-id: 33acba1b
- name: NL - zhuhai.uk 02
  type: vless
  server: bridge.meshbeat.online
  port: 443
  uuid: 1f619326-cd93-4d6b-aebe-e0b5f8831d02
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: yahoo.com
  client-fingerprint: chrome
  reality-opts:
    public-key: XZa7f7bABj7lY4HuLopVCBBBYTu-RB7QyIZ96njvYwo
    short-id: 7bcfc0bc
proxy-groups:
- name: EXTRA-LIVE
  type: select
  proxies:
  - GB - zhuhai.uk 02
  - GB - zhuhai.uk 04
  - GB - zhuhai.uk 03
  - NL - zhuhai.uk 02
