proxies:
- name: FR - zhuhai.uk 01
  type: vless
  server: 45.131.212.231
  port: 443
  uuid: 19513b1b-d29a-4f3e-ba9a-888261e4e048
  udp: true
  network: tcp
  flow: xtls-rprx-vision
  tls: true
  servername: sellflow.org
  client-fingerprint: firefox
  reality-opts:
    public-key: SbVKOEMjK0sIlbwg4akyBg5mL5KZwwB-ed4eEE7YnRc
proxy-groups:
- name: EXTRA-LIVE
  type: select
  proxies:
  - FR - zhuhai.uk 01
